
project_id = "uxccfhptochnfomurulr"

[functions.webhook-evolution-yelena]
verify_jwt = false

[functions.webhook-evolution-canarana]
verify_jwt = false

[functions.webhook-evolution-souto]
verify_jwt = false

[functions.webhook-evolution-joao]
verify_jwt = false

[functions.webhook-evolution-america]
verify_jwt = false

[functions.webhook-evolution-gerentelojas]
verify_jwt = false

[functions.webhook-evolution-gerenteexterno]
verify_jwt = false

// ... mantenha demais configurações do projeto
