"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.supabase = void 0;
// This file is automatically generated. Do not edit it directly.
var supabase_js_1 = require("@supabase/supabase-js");
var SUPABASE_URL = "https://uxccfhptochnfomurulr.supabase.co";
var SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4Y2NmaHB0b2NobmZvbXVydWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTg2MDAsImV4cCI6MjA2Mzc3NDYwMH0.FSxZR0jk7HjNxKegdULP49BnkFUmwiiUbgbZUucE_no";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
exports.supabase = (0, supabase_js_1.createClient)(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
