// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxccfhptochnfomurulr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4Y2NmaHB0b2NobmZvbXVydWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTg2MDAsImV4cCI6MjA2Mzc3NDYwMH0.FSxZR0jk7HjNxKegdULP49BnkFUmwiiUbgbZUucE_no";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

